### ISSUE TITLE
Not a real isssue but...

### ISSUE THREAD

**Issue by guigast** [openscopeproject/MultiScreenSaver#2]
I would like to use this screen server to show Cacti images:
[https://github.com/Cacti/cacti](url)
The point is that the transition between network map is very ugly, i would like to switch directly from an image to the next one whitout the shufle.
Could you make an update with this options please?

Thank you very much

**Comment by qu1ck** [comment]
Assuming I understood you correctly and you mean the ugly part is blend transition and not the "shuffle", done:
https://github.com/openscopeproject/MultiScreenSaver/releases/tag/v1.2
